-- -------------------------------------------------------------
-- SQL SEED DATA FOR "BOOKS I OWN" DATABASE
-- Built exactly from the user's authentic spreadsheet data:
-- Contains exactly 130 books and their genre mapping associations.
-- -------------------------------------------------------------

-- Clean existing data
TRUNCATE TABLE book_genres CASCADE;
TRUNCATE TABLE books CASCADE;
TRUNCATE TABLE taxonomies CASCADE;

-- Insert canonical system taxonomies list
INSERT INTO taxonomies (id, genres, work_types, literary_periods, publishers, formats, conditions, content_types)
VALUES ('system', 
  ARRAY['Classics', 'Victorian', 'American', 'Russian', 'Translated', 'Literary', 'Philosophy', 'History', 'Politics', 'Essays', 'Biography', 'Autobiography', 'Memoir', 'Criticism', 'Science Fiction', 'Mystery', 'Dystopian', 'Detective Fiction', 'Historical Fiction', 'Fantasy', 'Short Stories Collection', 'Adventure', 'Drama', 'Horror', 'Satire', 'Evolution', 'Science', 'Biology', 'Natural History', 'Non-Fiction'],
  ARRAY['Novel', 'Novella', 'Epic Poetry', 'Play', 'Philosophical Treatise', 'Historical Account', 'Essay Collection', 'Critical Study', 'Scientific Treatise', 'Scientific Study', 'Short Story Collection', 'Children''s Novel', 'Anthology', 'Poetry', 'Play Collection', 'Folklore Collection', 'Novel Collection'],
  ARRAY['Classical Antiquity', 'Middle Ages', 'Early Modern', 'Enlightenment', 'Romanticism', 'American Renaissance', 'Victorian', 'Realism', 'Naturalism', 'Modernism', 'Golden Age of Science Fiction', 'Golden Age Science Fiction', 'Postmodernism', '20th Century', 'Contemporary', 'Scientific Revolution', '19th Century', 'Soviet Literature', 'Soviet Era', '20th Century American', 'Contemporary Horror', 'Early Science Fiction', 'Techno-thriller'],
  ARRAY['Penguin', 'Penguin Classics', 'Penguin Modern Classics', 'Oxford World''s Classics', 'Everyman''s Library', 'Vintage', 'Vintage International', 'Signet', 'Signet Classics', 'Bantam Classics', 'Barnes & Noble Classics', 'W. W. Norton & Company', 'Farrar, Straus and Giroux', 'Scribner', 'Macmillan', 'Wordsworth Classics', 'Viking Press', 'Hogarth Press', 'Progress Publishers', 'World''s Classics', 'John Murray', 'Fawcett Publications', 'Laurel-Leaf (Dell Publishing)', 'Oxford University Press', 'Macmillan & Co. Ltd.', 'Webster Division, McGraw-Hill Book Company', 'Short Story International', 'Embassy Books', 'Pocket Books', 'Dell Yearling', 'Pan Books', 'Watermill Classics', 'Ballantine Books', 'Del Rey / Ballantine Books', 'Townsend Library', 'Om Books International', 'Yearling', 'Washington Square Press', 'Alfred A. Knopf', 'Heritage Press', 'Princeton University Press', 'Henry Holt', 'Abhishek Publications', 'Tor Fantasy', 'Corgi Books', 'Chelsea House', 'Dover Thrift', 'Fawcett Crest', 'Dell Books', 'Progress Publishers Moscow', 'Little, Brown and Company', 'Meridian Classics', 'Canterbury Classics', 'Twayne Publishers', 'Routledge Classics', 'Random House', 'Scribner''s', 'Hill and Wang', 'Cengage Learning', 'Schirmer Books', 'Harvard University Press'],
  ARRAY['Paperback', 'Hardback', 'Other'],
  ARRAY['Like New', 'Good', 'Fair', 'Poor'],
  ARRAY['Fiction', 'Non-Fiction']
);

-- Insert 130 High-Fidelity Books matching sheet exactly
INSERT INTO books (book_id, title, author, author_nationality, content_type, work_type, literary_period, read_status, format, condition, publisher, published_year, page_count, purchase_date, primary_genre) VALUES
('B0001', 'The Naked Sun', 'Isaac Asimov', 'United States', 'Fiction', 'Novel', 'Golden Age of Science Fiction', 'Unread', 'Paperback', 'Good', 'Fawcett Publications', 1957, 223, 'Unknown', 'Science Fiction'),
('B0002', 'The Giver', 'Lois Lowry', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Good', 'Laurel-Leaf (Dell Publishing)', 1993, 180, 'Unknown', 'Science Fiction'),
('B0003', 'The Moonstone', 'Wilkie Collins', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Hardback', 'Poor', 'Oxford University Press', 1868, 521, 'Unknown', 'Mystery'),
('B0004', 'The Trumpet-Major', 'Thomas Hardy', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Poor', 'Macmillan & Co. Ltd.', 1880, 381, 'Unknown', 'Historical Fiction'),
('B0005', 'The Greatest American Short Stories', 'Various Authors', 'United States', 'Fiction', 'Short Story Collection', '20th Century American', 'Unread', 'Hardback', 'Poor', 'Webster Division, McGraw-Hill Book Company', 1947, 391, 'Unknown', 'Short Stories Collection'),
('B0006', 'Tales of the Mountains and Steppes', 'Chinghiz Aitmatov', 'Kyrgyzstan', 'Fiction', 'Short Story Collection', 'Soviet Literature', 'Unread', 'Hardback', 'Poor', 'Progress Publishers', 1965, 289, 'Unknown', 'Russian'),
('B0007', 'Johnny and the Dead', 'Terry Pratchett', 'United Kingdom', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Hardback', 'Good', 'Transworld Publishers', 1993, 173, 'Unknown', 'Fantasy'),
('B0008', 'Adam Bede', 'George Eliot', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Good', 'Signet Classics', 1859, 510, 'Unknown', 'Victorian'),
('B0009', 'Ivanhoe', 'Sir Walter Scott', 'United Kingdom', 'Fiction', 'Novel', 'Romanticism', 'Unread', 'Hardback', 'Fair', 'Signet Classics', 1819, 508, 'Unknown', 'Historical Fiction'),
('B0010', 'Sons and Lovers', 'D. H. Lawrence', 'United Kingdom', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Hardback', 'Good', 'Bantam Classics', 1913, 416, 'Unknown', 'Classics'),
('B0011', 'Les Misérables', 'Victor Hugo', 'France', 'Fiction', 'Novel', 'Realism', 'Unread', 'Paperback', 'Good', 'Signet Classics', 1862, 1463, 'Unknown', 'Classics'),
('B0012', 'The Turn of the Screw and Other Short Fiction', 'Henry James', 'United States', 'Fiction', 'Short Story Collection', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Bantam Classics', 1898, 403, 'Unknown', 'Classics'),
('B0013', 'Short Story International No. 11', 'Various Authors', 'International', 'Fiction', 'Short Story Collection', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Short Story International', 1970, 166, 'Unknown', 'Literary'),
('B0014', 'The Very Best of Charles Dickens Short Stories', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Short Story Collection', 'Victorian', 'Unread', 'Paperback', 'Like New', 'Embassy Books', 1850, 287, 'Unknown', 'Classics'),
('B0015', 'The Complete Stories', 'Flannery O''Connor', 'United States', 'Fiction', 'Short Story Collection', 'Contemporary', 'Unread', 'Paperback', 'Like New', 'Farrar, Straus and Giroux', 1971, 555, 'Unknown', 'American'),
('B0016', 'Don Quixote', 'Miguel de Cervantes', 'Spain', 'Fiction', 'Novel', 'Early Modern', 'Unread', 'Paperback', 'Good', 'Signet Classics', 1605, 1037, 'Unknown', 'Classics'),
('B0017', 'Madame Bovary', 'Gustave Flaubert', 'France', 'Fiction', 'Novel', 'Realism', 'Read', 'Paperback', 'Fair', 'Bantam Classics', 1857, 424, 'Unknown', 'Classics'),
('B0018', 'One Day in the Life of Ivan Denisovich', 'Aleksandr Solzhenitsyn', 'Russia', 'Fiction', 'Novel', 'Soviet Era', 'Read', 'Paperback', 'Good', 'Bantam Windstone', 1962, 203, 'Unknown', 'Russian'),
('B0019', 'Song of Solomon', 'Toni Morrison', 'United States', 'Fiction', 'Novel', 'Postmodernism', 'Unread', 'Paperback', 'Fair', 'Signet', 1977, 341, 'Unknown', 'American'),
('B0020', 'The Red Pony', 'John Steinbeck', 'United States', 'Fiction', 'Novella', 'Modernism', 'Read', 'Paperback', 'Fair', 'Bantam Books', 1937, 120, 'Unknown', 'American'),
('B0021', 'The Great Gatsby', 'F. Scott Fitzgerald', 'United States', 'Fiction', 'Novel', 'Modernism', 'Read', 'Paperback', 'Good', 'Charles Scribner''s Sons', 1925, 182, 'Unknown', 'American'),
('B0022', 'The Pearl', 'John Steinbeck', 'United States', 'Fiction', 'Novella', 'Modernism', 'Read', 'Paperback', 'Poor', 'Penguin Books', 1947, 107, 'Unknown', 'American'),
('B0023', 'Of Mice and Men', 'John Steinbeck', 'United States', 'Fiction', 'Novella', 'Modernism', 'Read', 'Paperback', 'Poor', 'Penguin Books', 1937, 90, 'Unknown', 'American'),
('B0024', 'The Grapes of Wrath', 'John Steinbeck', 'United States', 'Fiction', 'Novel', 'Modernism', 'Read', 'Paperback', 'Poor', 'Penguin Modern Classics', 1939, 416, 'Unknown', 'American'),
('B0025', 'Ralph S. Mouse', 'Beverly Cleary', 'United States', 'Fiction', 'Children''s Novel', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Dell Yearling', 1982, 160, 'Unknown', 'American'),
('B0026', 'Ramona Quimby, Age 8', 'Beverly Cleary', 'United States', 'Fiction', 'Children''s Novel', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Dell Yearling', 1981, 188, 'Unknown', 'American'),
('B0027', 'East of Eden', 'John Steinbeck', 'United States', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Pan Books', 1952, 567, 'Unknown', 'American'),
('B0028', 'The Legend of Sleepy Hollow and Rip Van Winkle', 'Washington Irving', 'United States', 'Fiction', 'Short Story Collection', 'Romanticism', 'Read', 'Paperback', 'Fair', 'Watermill Classics', 1820, 83, 'Unknown', 'American'),
('B0029', 'Orlando', 'Virginia Woolf', 'United Kingdom', 'Fiction', 'Novel', 'Modernism', 'Read', 'Paperback', 'Poor', 'Penguin Modern Classics', 1928, 231, 'Unknown', 'Classics'),
('B0030', 'Eight Plus One', 'Robert Cormier', 'United States', 'Fiction', 'Children''s Novel', 'Contemporary', 'Unread', 'Hardback', 'Good', 'Ballantine Books', 1966, 196, 'Unknown', 'American'),
('B0031', 'The War of the Worlds', 'H. G. Wells', 'United Kingdom', 'Fiction', 'Novel', 'Early Science Fiction', 'Unread', 'Hardback', 'Fair', 'Signet Classics', 1898, 215, 'Unknown', 'Science Fiction'),
('B0032', 'Pet Sematary', 'Stephen King', 'United States', 'Fiction', 'Novel', 'Contemporary Horror', 'Unread', 'Hardback', 'Poor', 'Signet Fiction', 1983, 410, 'Unknown', 'Fantasy'),
('B0033', '2061: Odyssey Three', 'Arthur C. Clarke', 'United Kingdom', 'Fiction', 'Novel', 'Science Fiction', 'Unread', 'Paperback', 'Good', 'Del Rey / Ballantine Books', 1987, 271, 'Unknown', 'Science Fiction'),
('B0034', 'Jurassic Park', 'Michael Crichton', 'United States', 'Fiction', 'Novel', 'Techno-thriller', 'Read', 'Paperback', 'Fair', 'Ballantine Books', 1990, 399, 'Unknown', 'Science Fiction'),
('B0035', 'White Fang', 'Jack London', 'United States', 'Fiction', 'Novel', 'Naturalism', 'Unread', 'Paperback', 'Like New', 'Townsend Library', 1906, 282, 'Unknown', 'American'),
('B0036', 'It', 'Stephen King', 'United States', 'Fiction', 'Novel', 'Contemporary Horror', 'Unread', 'Paperback', 'Poor', 'Signet', 1986, 1093, 'Unknown', 'Fantasy'),
('B0037', 'Crime and Punishment', 'Fyodor Dostoevsky', 'Russia', 'Fiction', 'Novel', 'Realism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1866, 499, 'Unknown', 'Russian'),
('B0038', 'A Portrait of the Artist as a Young Man', 'James Joyce', 'Ireland', 'Fiction', 'Novel', 'Modernism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1916, 218, 'Unknown', 'Classic'),
('B0039', 'Anna Karenina', 'Leo Tolstoy', 'Russia', 'Fiction', 'Novel', 'Realism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1877, 888, 'Unknown', 'Russian'),
('B0040', 'Barnaby Rudge', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Paperback', 'Like New', 'Wordsworth Classics', 1841, 648, 'Unknown', 'Victorian'),
('B0041', 'Ulysses', 'James Joyce', 'Ireland', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Paperback', 'Like New', 'Wordsworth Classics', 1922, 681, 'Unknown', 'Classics'),
('B0042', 'The Golden Compass', 'Philip Pullman', 'United Kingdom', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Poor', 'Yearling', 1995, 499, 'Unknown', 'Fantasy'),
('B0043', 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Good', 'Washington Square Press', 2017, 389, 'Unknown', 'American'),
('B0044', 'Eragon', 'Christopher Paolini', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Good', 'Alfred A. Knopf', 2002, 503, 'Unknown', 'Fantasy'),
('B0045', 'Memoirs of a Geisha', 'Arthur Golden', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Paperback', 'Good', 'Vintage Contemporaries', 1997, 434, 'Unknown', 'Translated'),
('B0046', 'Jane Eyre', 'Charlotte Brontë', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Paperback', 'Good', 'Vintage', 1847, 545, 'Unknown', 'Victorian'),
('B0047', 'As I Lay Dying', 'William Faulkner', 'United States', 'Fiction', 'Novel', 'Modernism', 'Read', 'Paperback', 'Like New', 'W. W. Norton (Norton Critical Editions)', 1930, 384, 'Unknown', 'American'),
('B0048', 'Parade''s End', 'Ford Madox Ford', 'United Kingdom', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Hardback', 'Like New', 'Everyman''s Library', 1924, 906, 'Unknown', 'Literary'),
('B0049', 'Villette', 'Charlotte Brontë', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Like New', 'Everyman''s Library', 1853, 657, 'Unknown', 'Victorian'),
('B0050', 'Lorna Doone', 'R. D. Blackmore', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Like New', 'Wordsworth Classics', 1869, 566, 'Unknown', 'Classics'),
('B0051', 'Death of a Salesman', 'Arthur Miller', 'United States', 'Fiction', 'Play', 'Contemporary', 'Read', 'Paperback', 'Like New', 'Penguin Classics', 1949, 112, 'Unknown', 'American'),
('B0052', 'Billy Budd and Other Stories', 'Herman Melville', 'United States', 'Fiction', 'Short Story Collection', 'American Renaissance', 'Read', 'Paperback', 'Good', 'Everyman''s Library', 1924, 295, 'Unknown', 'American'),
('B0053', 'The Devils', 'Fyodor Dostoevsky', 'Russia', 'Fiction', 'Novel', 'Realism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1872, 671, 'Unknown', 'Russian'),
('B0054', 'The Count of Monte Cristo', 'Alexandre Dumas', 'France', 'Fiction', 'Novel', 'Romanticism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1844, 1122, 'Unknown', 'Classics'),
('B0055', 'Frankenstein', 'Mary Shelley', 'United Kingdom', 'Fiction', 'Novel', 'Romanticism', 'Read', 'Paperback', 'Good', 'Penguin Classics', 1818, 273, 'Unknown', 'Classics'),
('B0056', 'The Three Musketeers', 'Alexandre Dumas', 'France', 'Fiction', 'Novel', 'Romanticism', 'Unread', 'Paperback', 'Like New', 'Om Books International', 1844, 636, 'Unknown', 'Classics'),
('B0057', 'Great Expectations', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Paperback', 'Like New', 'Barnes & Noble Classics', 1861, 483, 'Unknown', 'Victorian'),
('B0058', 'Dead Souls', 'Nikolai Gogol', 'Russia', 'Fiction', 'Novel', 'Realism', 'Read', 'Paperback', 'Like New', 'Om Books International', 1842, 405, 'Unknown', 'Russian'),
('B0059', 'The Mill on the Floss', 'George Eliot', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Like New', 'Om Books International', 1860, 541, 'Unknown', 'Victorian'),
('B0060', 'David Copperfield', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Like New', 'Om Books International', 1850, 872, 'Unknown', 'Victorian'),
('B0061', 'Far from the Madding Crowd', 'Thomas Hardy', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Fair', 'Macmillan', 1874, 447, 'Unknown', 'Victorian'),
('B0062', 'Tess of the d''Urbervilles', 'Thomas Hardy', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Good', 'Bantam Classics', 1891, 414, 'Unknown', 'Victorian'),
('B0063', 'The Strange Case of Dr. Jekyll and Mr. Hyde', 'Robert Louis Stevenson', 'United Kingdom', 'Fiction', 'Novella', 'Victorian', 'Read', 'Paperback', 'Good', 'Barnes & Noble Classics', 1886, 269, 'Unknown', 'Classics'),
('B0064', 'Heart of Darkness', 'Joseph Conrad', 'United Kingdom', 'Fiction', 'Novella', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Barnes & Noble Classics', 1899, 259, 'Unknown', 'Victorian'),
('B0065', 'The Return of the Native', 'Thomas Hardy', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Paperback', 'Good', 'Bantam Classics', 1878, 374, 'Unknown', 'Victorian'),
('B0066', 'White Nights and Other Stories', 'Fyodor Dostoevsky', 'Russia', 'Fiction', 'Short Story Collection', 'Realism', 'Read', 'Hardback', 'Like New', 'Abhishek Publications', 1848, 307, 'Unknown', 'Russian'),
('B0067', 'Lord of Chaos', 'Robert Jordan', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Hardback', 'Like New', 'Tor Fantasy', 1994, 716, 'Unknown', 'Fantasy'),
('B0068', 'A Tale of Two Cities', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Read', 'Paperback', 'Good', 'Barnes & Noble Classics', 1859, 429, 'Unknown', 'Victorian'),
('B0069', 'Phineas Finn', 'Anthony Trollope', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Poor', 'The World''s Classics', 1869, 383, 'Unknown', 'Victorian'),
('B0070', 'The Fires of Heaven', 'Robert Jordan', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Like New', 'Tor Fantasy', 1993, 830, 'Unknown', 'Fantasy'),
('B0071', 'Schubert and His Vienna', 'Otto Erich Deutsch', 'Austria', 'Non-Fiction', 'Biography', '20th Century', 'Unread', 'Hardback', 'Good', 'Alfred A. Knopf', 1946, 209, 'Unknown', 'Biography'),
('B0072', 'Little Dorrit', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Reading', 'Hardback', 'Like New', 'Everyman''s Library', 1857, 835, 'Unknown', 'Victorian'),
('B0073', 'Moby-Dick; or, The Whale', 'Herman Melville', 'United States', 'Fiction', 'Novel', 'American Renaissance', 'Read', 'Paperback', 'Like New', 'Om Books International', 1851, 575, 'Unknown', 'American'),
('B0074', 'Catch-22', 'Joseph Heller', 'United States', 'Fiction', 'Novel', 'Postmodernism', 'Read', 'Paperback', 'Poor', 'Corgi Books', 1961, 478, 'Unknown', 'American'),
('B0075', 'Fahrenheit 451', 'Ray Bradbury', 'United States', 'Fiction', 'Novel', 'Dystopian', 'Read', 'Paperback', 'Fair', 'Simon & Schuster', 1953, 249, 'Unknown', 'Science Fiction'),
('B0076', 'Lucky Starr and the Big Mercury Oceans', 'Isaac Asimov', 'United States', 'Fiction', 'Novel', 'Golden Age Science Fiction', 'Unread', 'Paperback', 'Fair', 'Signet', 1956, 143, 'Unknown', 'Science Fiction'),
('B0077', 'A Man for All Seasons', 'Robert Bolt', 'United Kingdom', 'Fiction', 'Play', 'Contemporary', 'Read', 'Paperback', 'Good', 'Vintage Books', 1960, 95, 'Unknown', 'Classics'),
('B0078', 'Major Literary Characters: Ahab', 'Harold Bloom', 'United States', 'Non-Fiction', 'Criticism', 'Contemporary', 'Unread', 'Hardback', 'Like New', 'Chelsea House', 2007, 247, 'Unknown', 'Criticism'),
('B0079', 'Anthem', 'Ayn Rand', 'United States', 'Fiction', 'Novella', 'Dystopian', 'Unread', 'Paperback', 'Like New', 'Signet', 1938, 253, 'Unknown', 'Dystopian'),
('B0080', 'The Crosstime Engineer', 'Leo Frankowski', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Ballantine Books', 1986, 259, 'Unknown', 'Science Fiction'),
('B0081', 'The Outsiders', 'S. E. Hinton', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Paperback', 'Poor', 'Speak', 1967, 180, 'Unknown', 'American'),
('B0082', 'All Quiet on the Western Front', 'Erich Maria Remarque', 'Germany', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Fawcett Crest', 1929, 295, 'Unknown', 'Classics'),
('B0083', 'Slaughterhouse-Five', 'Kurt Vonnegut', 'United States', 'Fiction', 'Novel', 'Postmodernism', 'Unread', 'Paperback', 'Poor', 'Dell Books', 1969, 215, 'Unknown', 'American'),
('B0084', 'Lord of the Flies', 'William Golding', 'United Kingdom', 'Fiction', 'Novel', 'Contemporary', 'Unread', 'Paperback', 'Poor', 'Perigee Books', 1954, 208, 'Unknown', 'Classics'),
('B0085', 'A Farewell to Arms', 'Ernest Hemingway', 'United States', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Hardback', 'Good', 'Scribner', 1929, 331, 'Unknown', 'American'),
('B0086', 'The Same Old Story', 'Various Authors', 'Russia', 'Fiction', 'Short Story Collection', 'Soviet Literature', 'Unread', 'Hardback', 'Fair', 'Progress Publishers Moscow', 1970, 390, 'Unknown', 'Russian'),
('B0087', 'The Catcher in the Rye', 'J. D. Salinger', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Poor', 'Little, Brown and Company', 1951, 214, 'Unknown', 'American'),
('B0088', 'The Life and Opinions of Tristram Shandy, Gentleman', 'Laurence Sterne', 'United Kingdom', 'Fiction', 'Novel', 'Enlightenment', 'Unread', 'Paperback', 'Fair', 'Meridian Classics', 1759, 546, 'Unknown', 'Classics'),
('B0089', 'Tender Is the Night', 'F. Scott Fitzgerald', 'United States', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Paperback', 'Poor', 'Collier Books', 1934, 313, 'Unknown', 'American'),
('B0090', 'Greek Drama: Aeschylus, Sophocles, Euripides, Aristophanes', 'Various Authors', 'Greece', 'Fiction', 'Play Collection', 'Classical Antiquity', 'Unread', 'Paperback', 'Good', 'Bantam Classics', 450, 337, 'Unknown', 'Classics'),
('B0091', 'Fyodor Dostoevsky', 'William J. Leatherbarrow', 'United Kingdom', 'Non-Fiction', 'Criticism', 'Contemporary', 'Unread', 'Hardback', 'Good', 'Twayne Publishers', 1981, 185, 'Unknown', 'Criticism'),
('B0092', 'The Birds Fall Down', 'Rebecca West', 'United Kingdom', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Hardback', 'Fair', 'The Viking Press', 1966, 435, 'Unknown', 'Literary'),
('B0093', 'The Norton Anthology of English Literature: The Victorian Age (Volume E)', 'Various Authors', 'United Kingdom', 'Non-Fiction', 'Anthology', 'Victorian', 'Unread', 'Paperback', 'Like New', 'W. W. Norton & Company', 1837, 868, 'Unknown', 'Criticism'),
('B0094', 'The Norton Anthology of English Literature: The Twentieth Century and After (Volume F)', 'Various Authors', 'United Kingdom', 'Non-Fiction', 'Anthology', '20th Century', 'Unread', 'Paperback', 'Like New', 'W. W. Norton & Company', 1900, 1183, 'Unknown', 'Criticism'),
('B0095', 'The Norton Anthology of English Literature: The Romantic Period (Volume D)', 'Various Authors', 'United Kingdom', 'Non-Fiction', 'Anthology', 'Romanticism', 'Unread', 'Paperback', 'Like New', 'W. W. Norton & Company', 1789, 1014, 'Unknown', 'Criticism'),
('B0096', 'Robinson Crusoe', 'Daniel Defoe', 'United Kingdom', 'Fiction', 'Novel', 'Enlightenment', 'Read', 'Hardback', 'Like New', 'Barnes & Noble Classics', 1719, 265, 'Unknown', 'Classics'),
('B0097', 'The Classic Fairy Tales', 'Iona Opie; Peter Opie', 'United Kingdom', 'Non-Fiction', 'Folklore Collection', '20th Century', 'Reading', 'Hardback', 'Good', 'Oxford University Press', 1974, 336, 'Unknown', 'History'),
('B0098', 'The House of the Seven Gables', 'Nathaniel Hawthorne', 'United States', 'Fiction', 'Novel', 'American Renaissance', 'Read', 'Paperback', 'Good', 'Signet Classics', 1851, 287, 'Unknown', 'American'),
('B0099', 'The Scarlet Letter', 'Nathaniel Hawthorne', 'United States', 'Fiction', 'Novel', 'American Renaissance', 'Read', 'Paperback', 'Good', 'Bantam Classics', 1850, 244, 'Unknown', 'American'),
('B0100', 'Daisy Miller and Other Stories', 'Henry James', 'United States', 'Fiction', 'Short Story Collection', 'Realism', 'Unread', 'Paperback', 'Fair', 'The World''s Classics', 1878, 300, 'Unknown', 'American'),
('B0101', 'Othello', 'William Shakespeare', 'United Kingdom', 'Fiction', 'Play', 'Early Modern', 'Unread', 'Paperback', 'Like New', 'Signet Classics', 1603, 246, 'Unknown', 'Classics'),
('B0102', 'The Taming of the Shrew', 'William Shakespeare', 'United Kingdom', 'Fiction', 'Play', 'Early Modern', 'Unread', 'Paperback', 'Good', 'Signet Classics', 1592, 223, 'Unknown', 'Classics'),
('B0103', 'Paradise Lost and Paradise Regained', 'John Milton', 'United Kingdom', 'Fiction', 'Poetry', 'Early Modern', 'Unread', 'Paperback', 'Like New', 'Signet Classics', 1667, 360, 'Unknown', 'Classics'),
('B0104', 'The Odyssey', 'Homer', 'Ancient Greece', 'Fiction', 'Epic Poetry', 'Classical Antiquity', 'Unread', 'Paperback', 'Like New', 'Farrar, Straus and Giroux', -800, 512, 'Unknown', 'Classics'),
('B0105', 'The Woman in White', 'Wilkie Collins', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Paperback', 'Like New', 'Penguin Popular Classics', 1859, 567, 'Unknown', 'Victorian'),
('B0106', 'Martin Chuzzlewit', 'Charles Dickens', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Good', 'Dodd, Mead & Company', 1844, 752, 'Unknown', 'Victorian'),
('B0107', 'The Basic Writings of Bertrand Russell', 'Bertrand Russell', 'United Kingdom', 'Non-Fiction', 'Philosophy', '20th Century', 'Unread', 'Paperback', 'Like New', 'Routledge Classics', 1903, 749, 'Unknown', 'Philosophy'),
('B0108', 'Ethan Frome', 'Edith Wharton', 'United States', 'Fiction', 'Novella', 'Modernism', 'Read', 'Paperback', 'Fair', 'Macmillan', 1911, 144, 'Unknown', 'American'),
('B0109', 'The Red Badge of Courage', 'Stephen Crane', 'United States', 'Fiction', 'Novel', 'American Renaissance', 'Unread', 'Paperback', 'Poor', 'Washington Square Press', 1895, 188, 'Unknown', 'American'),
('B0110', 'The Turn of the Screw and Other Short Stories', 'Henry James', 'United States', 'Fiction', 'Short Story Collection', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Bantam Classics', 1898, 403, 'Unknown', 'Classics'),
('B0111', 'Flowers for Algernon', 'Daniel Keyes', 'United States', 'Fiction', 'Novel', 'Contemporary', 'Read', 'Paperback', 'Fair', 'Bantam Books', 1966, 216, 'Unknown', 'Science Fiction'),
('B0112', 'The Red Badge of Courage', 'Stephen Crane', 'United States', 'Fiction', 'Novel', 'American Renaissance', 'Unread', 'Paperback', 'Good', 'Bantam Classics', 1895, 134, 'Unknown', 'American'),
('B0113', 'The Mouse and the Motorcycle', 'Beverly Cleary', 'United States', 'Fiction', 'Children''s Novel', 'Contemporary', 'Read', 'Paperback', 'Fair', 'Dell Yearling', 1965, 158, 'Unknown', 'American'),
('B0114', 'Light in August', 'William Faulkner', 'United States', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Paperback', 'Fair', 'Vintage International', 1932, 512, 'Unknown', 'American'),
('B0115', 'Dracula', 'Bram Stoker', 'Ireland', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Good', 'Dodd, Mead & Company', 1897, 430, 'Unknown', 'Classics'),
('B0116', 'The Seagull Reader: Literature', 'Various Authors', 'United States', 'Non-Fiction', 'Anthology', 'Contemporary', 'Unread', 'Paperback', 'Good', 'W. W. Norton & Company', 2005, 1243, 'Unknown', 'Criticism'),
('B0117', 'The Short Stories of Ernest Hemingway', 'Ernest Hemingway', 'United States', 'Fiction', 'Short Story Collection', 'Modernism', 'Unread', 'Hardback', 'Like New', 'Charles Scribner''s Sons', 1938, 499, 'Unknown', 'American'),
('B0118', 'Wuthering Heights', 'Emily Brontë', 'United Kingdom', 'Fiction', 'Novel', 'Victorian', 'Unread', 'Hardback', 'Fair', 'Dodd, Mead & Company', 1847, 355, 'Unknown', 'Classics'),
('B0119', 'Towards Zero', 'Agatha Christie', 'United Kingdom', 'Fiction', 'Novel', 'Modernism', 'Unread', 'Hardback', 'Like New', 'Bantam Books', 1944, 178, 'Unknown', 'Mystery'),
('B0120', 'The Essays of Virginia Woolf, Volume 5: 1929–1932', 'Virginia Woolf', 'United Kingdom', 'Non-Fiction', 'Essays', 'Modernism', 'Unread', 'Hardback', 'Like New', 'The Hogarth Press', 2009, 705, 'Unknown', 'Essays'),
('B0121', 'The Little Prince', 'Antoine de Saint-Exupéry', 'France', 'Fiction', 'Novella', 'Modernism', 'Read', 'Hardback', 'Good', 'Houghton Mifflin Harcourt', 1943, 60, 'Unknown', 'Classics'),
('B0122', 'Classic Music: Expression, Form and Style', 'Various Authors', 'United States', 'Non-Fiction', 'History', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Schirmer Books', 1985, 475, 'Unknown', 'History'),
('B0123', 'H. G. Wells: 6 Novels', 'H. G. Wells', 'United Kingdom', 'Fiction', 'Novel Collection', 'Modernism', 'Unread', 'Hardback', 'Like New', 'Canterbury Classics', 1895, 639, 'Unknown', 'Science Fiction'),
('B0124', 'Cathedral, Forge and Waterwheel: Technology and Invention in the Middle Ages', 'Frances Gies; Joseph Gies', 'United States', 'Non-Fiction', 'History', 'Middle Ages', 'Unread', 'Hardback', 'Good', 'HarperCollins', 1994, 357, 'Unknown', 'History'),
('B0125', 'A Contemporary World History 1917–1945', 'Various Authors', 'Russia', 'Non-Fiction', 'History', '20th Century', 'Unread', 'Hardback', 'Fair', 'Progress Publishers Moscow', 1970, 717, 'Unknown', 'History'),
('B0126', 'Changes in the Land: Indians, Colonists, and the Ecology of New England', 'William Cronon', 'United States', 'Non-Fiction', 'History', 'Contemporary', 'Unread', 'Paperback', 'Fair', 'Hill and Wang', 1983, 241, 'Unknown', 'History'),
('B0127', 'Western Civilization, Volume II: Since 1500', 'Various Authors', 'United States', 'Non-Fiction', 'History', 'Early Modern', 'Unread', 'Paperback', 'Good', 'Cengage Learning', 1500, 701, 'Unknown', 'History'),
('B0128', 'The Lives of the Greatest Composers', 'Harold C. Schonberg', 'United States', 'Non-Fiction', 'Biography', 'Contemporary', 'Reading', 'Hardback', 'Good', 'W. W. Norton & Company', 1970, 653, 'Unknown', 'Biography'),
('B0129', 'The Classical Style: Haydn, Mozart, Beethoven', 'Charles Rosen', 'United States', 'Non-Fiction', 'Criticism', 'Contemporary', 'Unread', 'Paperback', 'Good', 'W. W. Norton & Company', 1971, 533, 'Unknown', 'Criticism'),
('B0130', 'The Platypus and the Mermaid and Other Figments of the Classifying Imagination', 'Harriet Ritvo', 'United States', 'Non-Fiction', 'History', 'Contemporary', 'Unread', 'Hardback', 'Good', 'Harvard University Press', 1997, 288, 'Unknown', 'History');

-- Insert exact genre tags mappings with correct primary status
INSERT INTO book_genres (book_id, genre, is_primary) VALUES
('B0001', 'Science Fiction', TRUE), ('B0001', 'Mystery', FALSE),
('B0002', 'Science Fiction', TRUE), ('B0002', 'Dystopian', FALSE),
('B0003', 'Mystery', TRUE), ('B0003', 'Detective Fiction', FALSE),
('B0004', 'Historical Fiction', TRUE), ('B0004', 'Victorian', FALSE),
('B0005', 'Short Stories Collection', TRUE), ('B0005', 'American', FALSE),
('B0006', 'Russian', TRUE), ('B0006', 'Translated', FALSE),
('B0007', 'Fantasy', TRUE),
('B0008', 'Victorian', TRUE), ('B0008', 'Classics', FALSE),
('B0009', 'Historical Fiction', TRUE), ('B0009', 'Classics', FALSE), ('B0009', 'Literary', FALSE),
('B0010', 'Classics', TRUE), ('B0010', 'Literary', FALSE),
('B0011', 'Classics', TRUE), ('B0011', 'Literary', FALSE), ('B0011', 'Translated', FALSE),
('B0012', 'Classics', TRUE), ('B0012', 'Literary', FALSE),
('B0013', 'Literary', TRUE), ('B0013', 'Translated', FALSE),
('B0014', 'Classics', TRUE), ('B0014', 'Literary', FALSE),
('B0015', 'American', TRUE), ('B0015', 'Literary', FALSE),
('B0016', 'Classics', TRUE), ('B0016', 'Literary', FALSE), ('B0016', 'Translated', FALSE),
('B0017', 'Classics', TRUE), ('B0017', 'Literary', FALSE), ('B0017', 'Translated', FALSE),
('B0018', 'Russian', TRUE), ('B0018', 'Literary', FALSE), ('B0018', 'Translated', FALSE),
('B0019', 'American', TRUE), ('B0019', 'Literary', FALSE),
('B0020', 'American', TRUE), ('B0020', 'Classics', FALSE), ('B0020', 'Literary', FALSE),
('B0021', 'American', TRUE), ('B0021', 'Classics', FALSE), ('B0021', 'Literary', FALSE),
('B0022', 'American', TRUE), ('B0022', 'Classics', FALSE), ('B0022', 'Literary', FALSE),
('B0023', 'American', TRUE), ('B0023', 'Classics', FALSE), ('B0023', 'Literary', FALSE),
('B0024', 'American', TRUE), ('B0024', 'Classics', FALSE), ('B0024', 'Literary', FALSE),
('B0025', 'American', TRUE),
('B0026', 'American', TRUE),
('B0027', 'American', TRUE), ('B0027', 'Classics', FALSE), ('B0027', 'Literary', FALSE),
('B0028', 'American', TRUE), ('B0028', 'Classics', FALSE), ('B0028', 'Literary', FALSE),
('B0029', 'Classics', TRUE), ('B0029', 'Literary', FALSE), ('B0029', 'Translated', FALSE),
('B0030', 'American', TRUE), ('B0030', 'Literary', FALSE), ('B0030', 'Classics', FALSE),
('B0031', 'Science Fiction', TRUE), ('B0031', 'Classics', FALSE), ('B0031', 'Literary', FALSE),
('B0032', 'Fantasy', TRUE), ('B0032', 'Mystery', FALSE), ('B0032', 'Literary', FALSE),
('B0033', 'Science Fiction', TRUE), ('B0033', 'Classics', FALSE), ('B0033', 'Literary', FALSE),
('B0034', 'Science Fiction', TRUE), ('B0034', 'Mystery', FALSE), ('B0034', 'Literary', FALSE),
('B0035', 'American', TRUE), ('B0035', 'Classics', FALSE), ('B0035', 'Literary', FALSE),
('B0036', 'Fantasy', TRUE), ('B0036', 'Mystery', FALSE), ('B0036', 'Literary', FALSE),
('B0037', 'Russian', TRUE), ('B0037', 'Classics', FALSE), ('B0037', 'Literary', FALSE),
('B0038', 'Classics', TRUE), ('B0038', 'Literary', FALSE), ('B0038', 'American', FALSE),
('B0039', 'Russian', TRUE), ('B0039', 'Classics', FALSE), ('B0039', 'Literary', FALSE),
('B0040', 'Victorian', TRUE), ('B0040', 'Classics', FALSE), ('B0040', 'Literary', FALSE),
('B0041', 'Classics', TRUE), ('B0041', 'Literary', FALSE), ('B0041', 'Translated', FALSE),
('B0042', 'Fantasy', TRUE), ('B0042', 'Mystery', FALSE), ('B0042', 'Literary', FALSE),
('B0043', 'American', TRUE), ('B0043', 'Literary', FALSE), ('B0043', 'Classics', FALSE),
('B0044', 'Fantasy', TRUE), ('B0044', 'Literary', FALSE), ('B0044', 'American', FALSE),
('B0045', 'Translated', TRUE), ('B0045', 'Literary', FALSE), ('B0045', 'Classics', FALSE),
('B0046', 'Victorian', TRUE), ('B0046', 'Classics', FALSE), ('B0046', 'Literary', FALSE),
('B0047', 'American', TRUE), ('B0047', 'Classics', FALSE), ('B0047', 'Literary', FALSE),
('B0048', 'Literary', TRUE), ('B0048', 'Classics', FALSE), ('B0048', 'Translated', FALSE),
('B0049', 'Victorian', TRUE), ('B0049', 'Classics', FALSE), ('B0049', 'Literary', FALSE),
('B0050', 'Classics', TRUE), ('B0050', 'Victorian', FALSE), ('B0050', 'Literary', FALSE),
('B0051', 'American', TRUE), ('B0051', 'Classics', FALSE), ('B0051', 'Literary', FALSE), ('B0051', 'Drama', FALSE),
('B0052', 'American', TRUE), ('B0052', 'Classics', FALSE), ('B0052', 'Literary', FALSE), ('B0052', 'Adventure', FALSE),
('B0053', 'Russian', TRUE), ('B0053', 'Classics', FALSE), ('B0053', 'Literary', FALSE), ('B0053', 'Politics', FALSE),
('B0054', 'Classics', TRUE), ('B0054', 'Translated', FALSE), ('B0054', 'Literary', FALSE), ('B0054', 'Adventure', FALSE), ('B0054', 'Historical Fiction', FALSE),
('B0055', 'Classics', TRUE), ('B0055', 'Fantasy', FALSE), ('B0055', 'Horror', FALSE), ('B0055', 'Science Fiction', FALSE), ('B0055', 'Literary', FALSE),
('B0056', 'Classics', TRUE), ('B0056', 'Translated', FALSE), ('B0056', 'Literary', FALSE), ('B0056', 'Adventure', FALSE),
('B0057', 'Victorian', TRUE), ('B0057', 'Classics', FALSE), ('B0057', 'Literary', FALSE), ('B0057', 'Translated', FALSE),
('B0058', 'Russian', TRUE), ('B0058', 'Classics', FALSE), ('B0058', 'Translated', FALSE), ('B0058', 'Literary', FALSE), ('B0058', 'Satire', FALSE),
('B0059', 'Victorian', TRUE), ('B0059', 'Classics', FALSE), ('B0059', 'Literary', FALSE), ('B0059', 'Translated', FALSE),
('B0060', 'Victorian', TRUE), ('B0060', 'Classics', FALSE), ('B0060', 'Literary', FALSE), ('B0060', 'Translated', FALSE),
('B0061', 'Victorian', TRUE), ('B0061', 'Classics', FALSE), ('B0061', 'Literary', FALSE),
('B0062', 'Victorian', TRUE), ('B0062', 'Classics', FALSE), ('B0062', 'Literary', FALSE),
('B0063', 'Classics', TRUE), ('B0063', 'Mystery', FALSE), ('B0063', 'Fantasy', FALSE), ('B0063', 'Literary', FALSE),
('B0064', 'Classics', TRUE), ('B0064', 'Literary', FALSE), ('B0064', 'Politics', FALSE),
('B0065', 'Victorian', TRUE), ('B0065', 'Classics', FALSE), ('B0065', 'Literary', FALSE),
('B0066', 'Russian', TRUE), ('B0066', 'Classics', FALSE), ('B0066', 'Translated', FALSE), ('B0066', 'Literary', FALSE),
('B0067', 'Fantasy', TRUE), ('B0067', 'American', FALSE), ('B0067', 'Literary', FALSE),
('B0068', 'Victorian', TRUE), ('B0068', 'Classics', FALSE), ('B0068', 'Literary', FALSE), ('B0068', 'History', FALSE),
('B0069', 'Victorian', TRUE), ('B0069', 'Classics', FALSE), ('B0069', 'Literary', FALSE), ('B0069', 'History', FALSE),
('B0070', 'Fantasy', TRUE), ('B0070', 'American', FALSE), ('B0070', 'Literary', FALSE), ('B0070', 'Classics', FALSE),
('B0071', 'Biography', TRUE), ('B0071', 'History', FALSE), ('B0071', 'Criticism', FALSE),
('B0072', 'Victorian', TRUE), ('B0072', 'Classics', FALSE), ('B0072', 'Literary', FALSE), ('B0072', 'History', FALSE),
('B0073', 'American', TRUE), ('B0073', 'Classics', FALSE), ('B0073', 'Literary', FALSE), ('B0073', 'Philosophy', FALSE),
('B0074', 'American', TRUE), ('B0074', 'Classics', FALSE), ('B0074', 'Literary', FALSE), ('B0074', 'Politics', FALSE),
('B0075', 'Science Fiction', TRUE), ('B0075', 'Dystopian', FALSE), ('B0075', 'American', FALSE), ('B0075', 'Classics', FALSE),
('B0076', 'Science Fiction', TRUE), ('B0076', 'American', FALSE), ('B0076', 'Classics', FALSE), ('B0076', 'Literary', FALSE),
('B0077', 'Classics', TRUE), ('B0077', 'Literary', FALSE), ('B0077', 'History', FALSE), ('B0077', 'Politics', FALSE),
('B0078', 'Criticism', TRUE), ('B0078', 'Literary', FALSE), ('B0078', 'American', FALSE), ('B0078', 'History', FALSE),
('B0079', 'Dystopian', TRUE), ('B0079', 'American', FALSE), ('B0079', 'Classics', FALSE), ('B0079', 'Philosophy', FALSE),
('B0080', 'Science Fiction', TRUE), ('B0080', 'American', FALSE), ('B0080', 'Fantasy', FALSE), ('B0080', 'Literary', FALSE),
('B0081', 'American', TRUE), ('B0081', 'Literary', FALSE), ('B0081', 'Classics', FALSE), ('B0081', 'History', FALSE),
('B0082', 'Classics', TRUE), ('B0082', 'Translated', FALSE), ('B0082', 'Literary', FALSE), ('B0082', 'History', FALSE),
('B0083', 'American', TRUE), ('B0083', 'Science Fiction', FALSE), ('B0083', 'Classics', FALSE), ('B0083', 'Literary', FALSE),
('B0084', 'Classics', TRUE), ('B0084', 'Literary', FALSE), ('B0084', 'Politics', FALSE), ('B0084', 'History', FALSE),
('B0085', 'American', TRUE), ('B0085', 'Classics', FALSE), ('B0085', 'Literary', FALSE), ('B0085', 'History', FALSE),
('B0086', 'Russian', TRUE), ('B0086', 'Translated', FALSE), ('B0086', 'Literary', FALSE), ('B0086', 'Classics', FALSE),
('B0087', 'American', TRUE), ('B0087', 'Classics', FALSE), ('B0087', 'Literary', FALSE), ('B0087', 'History', FALSE),
('B0088', 'Classics', TRUE), ('B0088', 'Literary', FALSE), ('B0088', 'History', FALSE), ('B0088', 'Philosophy', FALSE),
('B0089', 'American', TRUE), ('B0089', 'Classics', FALSE), ('B0089', 'Literary', FALSE), ('B0089', 'History', FALSE),
('B0090', 'Classics', TRUE), ('B0090', 'History', FALSE), ('B0090', 'Translated', FALSE), ('B0090', 'Literary', FALSE),
('B0091', 'Criticism', TRUE), ('B0091', 'Biography', FALSE), ('B0091', 'History', FALSE), ('B0091', 'Literary', FALSE),
('B0092', 'Literary', TRUE), ('B0092', 'Classics', FALSE), ('B0092', 'History', FALSE), ('B0092', 'Mystery', FALSE),
('B0093', 'Criticism', TRUE), ('B0093', 'History', FALSE), ('B0093', 'Literary', FALSE), ('B0093', 'Victorian', FALSE),
('B0094', 'Criticism', TRUE), ('B0094', 'History', FALSE), ('B0094', 'Literary', FALSE), ('B0094', 'Politics', FALSE),
('B0095', 'Criticism', TRUE), ('B0095', 'History', FALSE), ('B0095', 'Literary', FALSE), ('B0095', 'Philosophy', FALSE),
('B0096', 'Classics', TRUE), ('B0096', 'Literary', FALSE), ('B0096', 'History', FALSE), ('B0096', 'Translated', FALSE),
('B0097', 'History', TRUE), ('B0097', 'Criticism', FALSE), ('B0097', 'Literary', FALSE), ('B0097', 'Classics', FALSE),
('B0098', 'American', TRUE), ('B0098', 'Classics', FALSE), ('B0098', 'Literary', FALSE), ('B0098', 'History', FALSE),
('B0099', 'American', TRUE), ('B0099', 'Classics', FALSE), ('B0099', 'Literary', FALSE), ('B0099', 'History', FALSE),
('B0100', 'American', TRUE), ('B0100', 'Classics', FALSE), ('B0100', 'Literary', FALSE), ('B0100', 'Translated', FALSE),
('B0101', 'Classics', TRUE), ('B0101', 'Literary', FALSE), ('B0101', 'History', FALSE), ('B0101', 'Politics', FALSE),
('B0102', 'Classics', TRUE), ('B0102', 'Literary', FALSE), ('B0102', 'History', FALSE), ('B0102', 'Politics', FALSE),
('B0103', 'Classics', TRUE), ('B0103', 'Literary', FALSE), ('B0103', 'Philosophy', FALSE), ('B0103', 'History', FALSE),
('B0104', 'Classics', TRUE), ('B0104', 'Translated', FALSE), ('B0104', 'Literary', FALSE), ('B0104', 'History', FALSE),
('B0105', 'Victorian', TRUE), ('B0105', 'Classics', FALSE), ('B0105', 'Literary', FALSE), ('B0105', 'Mystery', FALSE),
('B0106', 'Victorian', TRUE), ('B0106', 'Classics', FALSE), ('B0106', 'Literary', FALSE), ('B0106', 'History', FALSE),
('B0107', 'Philosophy', TRUE), ('B0107', 'Criticism', FALSE), ('B0107', 'Politics', FALSE), ('B0107', 'History', FALSE),
('B0108', 'American', TRUE), ('B0108', 'Classics', FALSE), ('B0108', 'Literary', FALSE), ('B0108', 'History', FALSE),
('B0109', 'American', TRUE), ('B0109', 'Classics', FALSE), ('B0109', 'Literary', FALSE), ('B0109', 'History', FALSE),
('B0110', 'American', TRUE), ('B0110', 'Classics', FALSE), ('B0110', 'Literary', FALSE), ('B0110', 'Mystery', FALSE),
('B0111', 'Science Fiction', TRUE), ('B0111', 'American', FALSE), ('B0111', 'Classics', FALSE), ('B0111', 'Literary', FALSE),
('B0112', 'American', TRUE), ('B0112', 'Classics', FALSE), ('B0112', 'Literary', FALSE), ('B0112', 'History', FALSE),
('B0113', 'American', TRUE), ('B0113', 'Literary', FALSE), ('B0113', 'Classics', FALSE), ('B0113', 'Fantasy', FALSE),
('B0114', 'American', TRUE), ('B0114', 'Classics', FALSE), ('B0114', 'Literary', FALSE), ('B0114', 'History', FALSE),
('B0115', 'Classics', TRUE), ('B0115', 'Fantasy', FALSE), ('B0115', 'Mystery', FALSE), ('B0115', 'Literary', FALSE),
('B0116', 'Criticism', TRUE), ('B0116', 'History', FALSE), ('B0116', 'Literary', FALSE), ('B0116', 'Politics', FALSE),
('B0117', 'American', TRUE), ('B0117', 'Classics', FALSE), ('B0117', 'Literary', FALSE), ('B0117', 'History', FALSE),
('B0118', 'Classics', TRUE), ('B0118', 'Victorian', FALSE), ('B0118', 'Literary', FALSE), ('B0118', 'History', FALSE),
('B0119', 'Mystery', TRUE), ('B0119', 'Classics', FALSE), ('B0119', 'Literary', FALSE), ('B0119', 'History', FALSE),
('B0120', 'Essays', TRUE), ('B0120', 'Criticism', FALSE), ('B0120', 'History', FALSE), ('B0120', 'Literary', FALSE),
('B0121', 'Classics', TRUE), ('B0121', 'Translated', FALSE), ('B0121', 'Literary', FALSE), ('B0121', 'Fantasy', FALSE),
('B0122', 'History', TRUE), ('B0122', 'Criticism', FALSE), ('B0122', 'Literary', FALSE), ('B0122', 'Philosophy', FALSE),
('B0123', 'Science Fiction', TRUE), ('B0123', 'Classics', FALSE), ('B0123', 'Literary', FALSE), ('B0123', 'History', FALSE),
('B0124', 'History', TRUE), ('B0124', 'Criticism', FALSE), ('B0124', 'Philosophy', FALSE), ('B0124', 'Literary', FALSE),
('B0125', 'History', TRUE), ('B0125', 'Politics', FALSE), ('B0125', 'Criticism', FALSE), ('B0125', 'Literary', FALSE),
('B0126', 'History', TRUE), ('B0126', 'Politics', FALSE), ('B0126', 'Criticism', FALSE), ('B0126', 'American', FALSE),
('B0127', 'History', TRUE), ('B0127', 'Politics', FALSE), ('B0127', 'Criticism', FALSE), ('B0127', 'Philosophy', FALSE),
('B0128', 'Biography', TRUE), ('B0128', 'History', FALSE), ('B0128', 'Criticism', FALSE), ('B0128', 'Literary', FALSE),
('B0129', 'Criticism', TRUE), ('B0129', 'History', FALSE), ('B0129', 'Philosophy', FALSE), ('B0129', 'Literary', FALSE),
('B0130', 'History', TRUE), ('B0130', 'Criticism', FALSE), ('B0130', 'Philosophy', FALSE), ('B0130', 'Literary', FALSE);
